export enum NotificationsType {
  ORDER_STATUS_UPDATE = 'ORDER_STATUS_UPDATE',
  ORDER_DETAILS_UPDATE = 'ORDER_DETAILS_UPDATE',
  // STORE_MANAGER
  STORE_MANAGER_NEW_ORDER = 'STORE_MANAGER_NEW_ORDER',
  STORE_MANAGER_REJECTED_ORDER = 'STORE_MANAGER_REJECTED_ORDER',
  STORE_MANAGER_NOT_DELIVERED_ORDER = 'STORE_MANAGER_NOT_DELIVERED_ORDER',
  // DELIVERY_MAN
  DELIVERY_MAN_NEW_ORDER = 'DELIVERY_MAN_NEW_ORDER',
  DELIVERY_MAN_PENDING_ORDER = 'DELIVERY_MAN_PENDING_ORDER',
  DELIVERY_MAN_REASSIGNED_ORDER = 'DELIVERY_MAN_REASSIGNED_ORDER',
}
