'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.sequelize.query(`DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_orders_status') THEN
          CREATE TYPE public."enum_orders_status" AS ENUM (
            'initiated',
            'pending',
            'accepted',
            'preparing',
            'packed',
            'enRoute',
            'arrived',
            'delivered',
            'notDelivered',
            'canceled');
        END IF;
      END
      $$`);

    await queryInterface.sequelize.query(`DO $$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_orders_payment_type') THEN
            CREATE TYPE public."enum_orders_payment_type" AS ENUM (
              'cash',
              'card');
          END IF;
        END
        $$`);

    await queryInterface.sequelize.query(`DO $$
          BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_orders_payment_status') THEN
              CREATE TYPE public."enum_orders_payment_status" AS ENUM (
                'pending',
                'failed',
                'paid',
                'notPaid',
                'refunded');
            END IF;
          END
          $$`);

    await queryInterface.sequelize.query(`DO $$
          BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_orders_delivery_type') THEN
              CREATE TYPE public."enum_orders_delivery_type" AS ENUM (
                'immediate',
                'scheduled');
            END IF;
          END
        $$`);

    await queryInterface.sequelize.query(`CREATE TABLE public.orders (
      id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
      user_id int4 NULL,
      delivery_address_id int4 NULL,
      store_id int4 NULL,
      quantity int4 NULL,
      total_price numeric(10, 2) NULL,
      status public."enum_orders_status" DEFAULT 'initiated'::enum_orders_status NULL,
      payment_status public."enum_orders_payment_status" DEFAULT 'pending'::enum_orders_payment_status NULL,
      payment_type public."enum_orders_payment_type" NULL,
      created_at timestamptz NOT NULL,
      updated_at timestamptz NOT NULL,
      delivery_date timestamptz NULL,
      delivery_type public."enum_orders_delivery_type" DEFAULT 'scheduled'::enum_orders_delivery_type NULL,
      CONSTRAINT orders_pkey PRIMARY KEY (id)
    );`);
    await queryInterface.sequelize.query(
      `ALTER TABLE public.orders ADD CONSTRAINT orders_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id) ON DELETE CASCADE ON UPDATE CASCADE;`,
    );
    await queryInterface.sequelize.query(
      `ALTER TABLE public.orders ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE ON UPDATE CASCADE;`,
    );

    await queryInterface.sequelize.query(`CREATE TABLE public.order_products (
      id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
      order_id int4 NULL,
      product_id int4 NULL,
      quantity int4 NULL,
      total_price numeric(10, 2) DEFAULT 0 NULL,
      CONSTRAINT order_products_pkey PRIMARY KEY (id)
    );`);

    await queryInterface.sequelize.query(
      `ALTER TABLE public.order_products ADD CONSTRAINT order_products_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE ON UPDATE CASCADE;`,
    );
    await queryInterface.sequelize.query(
      `ALTER TABLE public.order_products ADD CONSTRAINT order_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE ON UPDATE CASCADE;`,
    );

    await queryInterface.sequelize.query(`CREATE TABLE public.order_product_modifiers (
      id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
      order_product_id int4 NULL,
      modifier_product_id int4 NULL,
      CONSTRAINT order_product_modifiers_pkey PRIMARY KEY (id)
    );`);

    await queryInterface.sequelize.query(
      `ALTER TABLE public.order_product_modifiers ADD CONSTRAINT order_product_modifiers_modifier_product_id_fkey FOREIGN KEY (modifier_product_id) REFERENCES public.modifier_products(id) ON DELETE CASCADE ON UPDATE CASCADE;`,
    );
    await queryInterface.sequelize.query(
      `ALTER TABLE public.order_product_modifiers ADD CONSTRAINT order_product_modifiers_order_product_id_fkey FOREIGN KEY (order_product_id) REFERENCES public.order_products(id) ON DELETE CASCADE ON UPDATE CASCADE;`,
    );
  },

  async down(queryInterface) {
    await queryInterface.sequelize.query(
      `ALTER TABLE IF EXISTS public.orders DROP CONSTRAINT IF EXISTS orders_store_id_fkey`,
    );
    await queryInterface.sequelize.query(
      `ALTER TABLE IF EXISTS public.orders DROP CONSTRAINT IF EXISTS orders_user_id_fkey`,
    );
    await queryInterface.sequelize.query('DROP TABLE public.orders;');

    await queryInterface.sequelize.query(
      `ALTER TABLE IF EXISTS public.orders DROP CONSTRAINT IF EXISTS order_products_order_id_fkey`,
    );
    await queryInterface.sequelize.query(
      `ALTER TABLE IF EXISTS public.orders DROP CONSTRAINT IF EXISTS order_products_product_id_fkey`,
    );
    await queryInterface.sequelize.query('DROP TABLE public.order_products;');

    await queryInterface.sequelize.query(
      `ALTER TABLE IF EXISTS public.orders DROP CONSTRAINT IF EXISTS order_product_modifiers_modifier_product_id_fkey`,
    );
    await queryInterface.sequelize.query(
      `ALTER TABLE IF EXISTS public.orders DROP CONSTRAINT IF EXISTS order_product_modifiers_order_product_id_fkey`,
    );
    await queryInterface.sequelize.query('DROP TABLE public.order_product_modifiers;');

    await queryInterface.sequelize.query(`DROP TYPE IF EXISTS public."enum_orders_status";`);
    await queryInterface.sequelize.query(`DROP TYPE IF EXISTS public."enum_orders_payment_type";`);
    await queryInterface.sequelize.query(
      `DROP TYPE IF EXISTS public."enum_orders_payment_status";`,
    );
    await queryInterface.sequelize.query(`DROP TYPE IF EXISTS public."enum_orders_delivery_type";`);
  },
};
